/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Propriety;

import Model.Propriety;

/**
 *
 * @author Carlos Gomez
 */
public class PhoneService extends javax.swing.JDialog {
    private Propriety propriety;
    /**
     * Creates new form PhoneService
     */
    public PhoneService(java.awt.Frame parent, boolean modal,Propriety propriety) {
        super(parent, modal);
        initComponents();
        this.propriety = propriety;
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblText1 = new javax.swing.JLabel();
        lblText2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblMortgage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/telemoveis.jpg"))); // NOI18N

        lblName.setText("jLabel1");

        lblText1.setText("jLabel1");

        lblText2.setText("jLabel1");

        jLabel1.setText("VALOR DA HIPOTECA - ");

        lblMortgage.setText("lblMortgage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblText2)
                                    .addComponent(lblText1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(lblName))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMortgage)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblName)
                .addGap(42, 42, 42)
                .addComponent(lblText1)
                .addGap(61, 61, 61)
                .addComponent(lblText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblMortgage))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblMortgage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblText1;
    private javax.swing.JLabel lblText2;
    // End of variables declaration//GEN-END:variables

private void init() {
        lblName.setText(propriety.getName());
       
        
        String html = "<html><body>Se um jogador possuir um dos<br>Serviços o aluguer será de<br>4 vezes a quantia indicada<br>"
                + "nos dados.</body></html>";
         lblText1.setText(html);
         
         html = "<html><body>Se um jogador possuir ambos<br>os Serviços o aluguer será de<br>10 vezes a quantia indicada<br>"
                + "nos dados.</body></html>";
         lblText2.setText(html);
         
         showMillion(propriety.getMortgage());
    }
    
    private void showMillion(float money){
       float million = money/ 1000000;
        
        if(million >=1){
            lblMortgage.setText(String.format("%.2fM", money/ 1000000.0));
        }else{
            lblMortgage.setText(String.format("%.2fK", money/ 1000.0));
        }
   }
}
