/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Propriety;

import Model.AppManager;
import Model.Propriety;
import java.awt.Color;

/**
 *
 * @author Carlos Gomez
 */
public class ProprietyCard extends javax.swing.JDialog {
    private Propriety propriety;
    /**
     * Creates new form ProprietyCard
     */
    public ProprietyCard(java.awt.Frame parent, boolean modal,Propriety propriety) {
        super(parent, modal);
        initComponents();
        this.propriety = propriety;
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPrecoRental = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPrecoHouse1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPrecoHouse2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblPrecoHouse3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblPrecoHouse4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblPrecoHotel = new javax.swing.JLabel();
        lblTxt = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblPrecoBuildHouse = new javax.swing.JLabel();
        lblPrecoBuildHotel = new javax.swing.JLabel();
        lblHipoteca = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelName.setText("jLabel1");

        jLabel1.setText("Título de Propriedade");

        jLabel2.setText("ALUGUER - SÓ DO TERRENO");

        jLabel3.setText("€");

        lblPrecoRental.setText("jLabel4");

        jLabel5.setText("\"                  Com 1 apartamento");

        lblPrecoHouse1.setText("jLabel6");

        jLabel7.setText("\"                  Com 2 apartamento");

        lblPrecoHouse2.setText("jLabel8");

        jLabel9.setText("\"                  Com 3 apartamento");

        lblPrecoHouse3.setText("jLabel10");

        jLabel11.setText("\"                  Com 4 apartamento");

        lblPrecoHouse4.setText("jLabel12");

        jLabel13.setText("ALUGUER COM HOTEL");

        lblPrecoHotel.setText("jLabel14");

        lblTxt.setText("Se um Jogador possuir todos os \\n\nterrenos de um grupo de cor, o aluguer\\n\ndos terrenos sem construções,1nnesse grupo, é a dobrar.");

        jLabel16.setText("Preço dos apartamentos");

        jLabel17.setText("Preço dos hoteis");

        jLabel18.setText("Valor da hipoteca do terreno");

        lblPrecoBuildHouse.setText("jLabel19");

        lblPrecoBuildHotel.setText("jLabel20");

        lblHipoteca.setText("jLabel21");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPrecoHouse2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPrecoHotel)
                                        .addComponent(lblPrecoHouse4)
                                        .addComponent(lblPrecoHouse3))
                                    .addComponent(lblPrecoHouse1)
                                    .addComponent(lblPrecoRental))
                                .addGap(31, 42, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(182, 182, 182)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrecoBuildHotel)
                                    .addComponent(lblHipoteca)
                                    .addComponent(lblPrecoBuildHouse))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblPrecoRental))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblPrecoHouse1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblPrecoHouse2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblPrecoHouse3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblPrecoHouse4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblPrecoHotel))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblPrecoBuildHouse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblPrecoBuildHotel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblHipoteca))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel lblHipoteca;
    private javax.swing.JLabel lblPrecoBuildHotel;
    private javax.swing.JLabel lblPrecoBuildHouse;
    private javax.swing.JLabel lblPrecoHotel;
    private javax.swing.JLabel lblPrecoHouse1;
    private javax.swing.JLabel lblPrecoHouse2;
    private javax.swing.JLabel lblPrecoHouse3;
    private javax.swing.JLabel lblPrecoHouse4;
    private javax.swing.JLabel lblPrecoRental;
    private javax.swing.JLabel lblTxt;
    // End of variables declaration//GEN-END:variables

    private void init() {
        labelName.setText("                                                              "+propriety.getName());
         
        //houses price
        float million = propriety.getRental()/1000000;
        
        if(million >=1){
            lblPrecoRental.setText(String.format("%.2fM",propriety.getRental()/ 1000000.0));
        }else{
            lblPrecoRental.setText(String.format("%.2fK", propriety.getRental()/ 1000.0));
        }
        
        million = propriety.getOneHouseRental()/1000000;
        
        if(million >=1){
            lblPrecoHouse1.setText(String.format("%.2fM",propriety.getOneHouseRental()/ 1000000.0));
        }else{
            lblPrecoHouse1.setText(String.format("%.2fK", propriety.getOneHouseRental()/ 1000.0));
        }
        
        million = propriety.getTwoHouseRental()/1000000;
        
        if(million >=1){
            lblPrecoHouse2.setText(String.format("%.2fM",propriety.getTwoHouseRental()/ 1000000.0));
        }else{
            lblPrecoHouse2.setText(String.format("%.2fK", propriety.getTwoHouseRental()/ 1000.0));
        }
        
        million = propriety.getThreeHouseRental()/1000000;
        
        if(million >=1){
            lblPrecoHouse3.setText(String.format("%.2fM",propriety.getThreeHouseRental()/ 1000000.0));
        }else{
            lblPrecoHouse3.setText(String.format("%.2fK", propriety.getThreeHouseRental()/ 1000.0));
        }
        
        million = propriety.getFourHouseRental()/1000000;
        
        if(million >=1){
            lblPrecoHouse4.setText(String.format("%.2fM",propriety.getFourHouseRental()/ 1000000.0));
        }else{
            lblPrecoHouse4.setText(String.format("%.2fK", propriety.getFourHouseRental()/ 1000.0));
        }
        
        million = propriety.getHotelRental()/1000000;
        
        if(million >=1){
            lblPrecoHotel.setText(String.format("%.2fM",propriety.getHotelRental()/ 1000000.0));
        }else{
            lblPrecoHotel.setText(String.format("%.2fK", propriety.getHotelRental()/ 1000.0));
        }
        
        //build 
        million = propriety.getBuildHouse()/1000000;
        
        if(million >=1){
            lblPrecoBuildHouse.setText(String.format("%.2fM",propriety.getBuildHouse()/ 1000000.0));
        }else{
            lblPrecoBuildHouse.setText(String.format("%.2fK", propriety.getBuildHouse()/ 1000.0));
        }
        
        million = propriety.getBuildHotel()/1000000;
        
        if(million >=1){
            lblPrecoBuildHotel.setText(String.format("%.2fM",propriety.getBuildHotel()/ 1000000.0));
        }else{
            lblPrecoBuildHotel.setText(String.format("%.2fK", propriety.getBuildHotel()/ 1000.0));
        }
        
        //mortgage
        million = propriety.getMortgage()/1000000;
        
        if(million >=1){
            lblHipoteca.setText(String.format("%.2fM",propriety.getMortgage()/ 1000000.0));
        }else{
            lblHipoteca.setText(String.format("%.2fK", propriety.getMortgage()/ 1000.0));
        }
 
        String html = "<html><body>Se um Jogador possuir todos os<br>terrenos de um grupo de cor,"
                + " o aluguer<br>dos terrenos sem construções,nesse grupo, é a dobrar.</body></html>";
        lblTxt.setText(html);
         
       
        switch(propriety.getColor()){
            case "Castanho":
                labelName.setOpaque(true);
                labelName.setBackground(new Color(102,51,0));
            break;
            case "Azul bebe":
                labelName.setOpaque(true);
                labelName.setBackground(new Color(51,204,255));
            break;
            case "Rosa":
                labelName.setOpaque(true);
                labelName.setBackground(new Color(255,20,147));
            break;
            case "Laranja":
                labelName.setOpaque(true);
                labelName.setBackground(new Color(255,102,0));
            break;
            case "Vermelho":
                labelName.setOpaque(true);
                labelName.setBackground(Color.RED);
            break;
            case "Amarelo":
                labelName.setOpaque(true);
                labelName.setBackground(Color.YELLOW);
            break;
            case "Verde":
                labelName.setOpaque(true);
                labelName.setBackground(new Color(0,128,0));
            break;
            case "Azul Escuro":
                labelName.setOpaque(true);
                labelName.setBackground(new Color(0,0,153));
            break;
        }
        
        this.getContentPane().setBackground(Color.WHITE);
        
    }
}
