/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ThreePlayer;

import Model.AppManager;
import Model.Player;
import View.FourPlayer.PlayersWindowFour;
import View.TwoPlayer.PlayersWindow;
import java.awt.List;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Gomez
 */
public class PaymentWindowThree extends javax.swing.JDialog {
    private int player;
    private LinkedList<Player> list;
    private PlayersWindowThree window;
    private PlayersWindowFour windowFour;
    /**
     * Creates new form PaymentWindowThree
     */
    public PaymentWindowThree(java.awt.Frame parent, boolean modal, int player,PlayersWindowThree window) {
        super(parent, modal);
        initComponents();
        this.player = player;
        this.window = window;
        init();
    }
    
    public PaymentWindowThree(java.awt.Frame parent, boolean modal, int player,PlayersWindowFour window) {
        super(parent, modal);
        initComponents();
        this.player = player;
        this.windowFour = window;
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPayer = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        cbPlayer = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Payer:");

        jLabel2.setText("Receiver:");

        jLabel3.setText("Quantity:");

        txtPayer.setEditable(false);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Pay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(txtPayer, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQuantity)
                            .addComponent(cbPlayer, 0, 128, Short.MAX_VALUE))))
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        closeWindow();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String insertText = txtQuantity.getText();
        
        try{
            int quantity = Integer.parseInt(insertText);
            int AuxQuantity;
            int money;
            
            if(quantity <0){
                showError(3);
            }else{
               switch(player){
                   case 1:
                       AuxQuantity = AppManager.INSTANCE.getPlayers(0).getMoney() - quantity;
               
                        if(AuxQuantity<0){
                            showError(4);
                        }else{
                            Player p = (Player) cbPlayer.getSelectedItem();
                            money = AppManager.INSTANCE.getPlayers(p.getNumber()-1).getMoney() +quantity;
                            AppManager.INSTANCE.getPlayers(0).setMoney(AuxQuantity);
                            AppManager.INSTANCE.getPlayers(p.getNumber()-1).setMoney(money);
                            if(window == null){
                                windowFour.setCurrentMoneyPLayer1();
                                windowFour.setCurrentMoneyPLayer2();
                                windowFour.setCurrentMoneyPLayer3();
                                windowFour.setCurrentMoneyPLayer4();
                                
                                windowFour.setRentMoney(p.getNumber(),quantity);
                            }else{
                                window.setCurrentMoneyPLayer1();
                                window.setCurrentMoneyPLayer2();
                                window.setCurrentMoneyPLayer3();
                                
                                
                                window.setRentMoney(p.getNumber(),quantity);
                            }
                            closeWindow();
                        }
                    break;
                    case 2:
                        AuxQuantity = AppManager.INSTANCE.getPlayers(1).getMoney() - quantity;
               
                        if(AuxQuantity<0){
                            showError(4);
                        }else{
                            Player p = (Player) cbPlayer.getSelectedItem();
                            money = AppManager.INSTANCE.getPlayers(p.getNumber()-1).getMoney() +quantity;
                            AppManager.INSTANCE.getPlayers(1).setMoney(AuxQuantity);
                            AppManager.INSTANCE.getPlayers(p.getNumber()-1).setMoney(money);
                            if(window == null){
                                windowFour.setCurrentMoneyPLayer1();
                                windowFour.setCurrentMoneyPLayer2();
                                windowFour.setCurrentMoneyPLayer3();
                                windowFour.setCurrentMoneyPLayer4();
                                
                                windowFour.setRentMoney(p.getNumber(),quantity);
                            }else{
                                window.setCurrentMoneyPLayer1();
                                window.setCurrentMoneyPLayer2();
                                window.setCurrentMoneyPLayer3();
                                
                                window.setRentMoney(p.getNumber(),quantity);
                            }
                            closeWindow();
                        }
                    break;
                    case 3:
                        AuxQuantity = AppManager.INSTANCE.getPlayers(2).getMoney() - quantity;

                        if(AuxQuantity<0){
                            showError(4);
                        }else{
                            Player p = (Player) cbPlayer.getSelectedItem();
                            money = AppManager.INSTANCE.getPlayers(p.getNumber()-1).getMoney() +quantity;
                            AppManager.INSTANCE.getPlayers(2).setMoney(AuxQuantity);
                            AppManager.INSTANCE.getPlayers(p.getNumber()-1).setMoney(money);
                            if(window == null){
                                windowFour.setCurrentMoneyPLayer1();
                                windowFour.setCurrentMoneyPLayer2();
                                windowFour.setCurrentMoneyPLayer3();
                                windowFour.setCurrentMoneyPLayer4();
                                
                                windowFour.setRentMoney(p.getNumber(),quantity);
                            }else{
                                window.setCurrentMoneyPLayer1();
                                window.setCurrentMoneyPLayer2();
                                window.setCurrentMoneyPLayer3();
                                
                                window.setRentMoney(p.getNumber(),quantity);
                            }
                            closeWindow();
                        }
                    break;
                    case 4:
                        AuxQuantity = AppManager.INSTANCE.getPlayers(3).getMoney() - quantity;
               
                        if(AuxQuantity<0){
                            showError(4);
                        }else{
                            Player p = (Player) cbPlayer.getSelectedItem();
                            money = AppManager.INSTANCE.getPlayers(p.getNumber()-1).getMoney() +quantity;
                            AppManager.INSTANCE.getPlayers(3).setMoney(AuxQuantity);
                            AppManager.INSTANCE.getPlayers(p.getNumber()-1).setMoney(money);
                            windowFour.setCurrentMoneyPLayer1();
                            windowFour.setCurrentMoneyPLayer2();
                            windowFour.setCurrentMoneyPLayer3();
                            windowFour.setCurrentMoneyPLayer4();
                            
                            windowFour.setRentMoney(p.getNumber(),quantity);
                            
                            closeWindow();
                        }
                    break;
               }
            }
        }catch(NumberFormatException e){
            showError(1);
        }catch(Exception e){
            showError(2);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbPlayer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtPayer;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

    private void init() {
        list = new LinkedList<>();
        LinkedList<Player> listAux = new LinkedList<>();
        list = AppManager.INSTANCE.getPlayers();
        
        for(Player p:list){
            listAux.add(p);
        }
        
        switch(player){
            case 1:
                txtPayer.setText(AppManager.INSTANCE.getPlayers(0).getName());
                listAux.remove(0);
                cbPlayer.setModel(new DefaultComboBoxModel(listAux.toArray()));
            break;
            case 2:
                txtPayer.setText(AppManager.INSTANCE.getPlayers(1).getName());
                listAux.remove(1);
                cbPlayer.setModel(new DefaultComboBoxModel(listAux.toArray()));
            break;
            case 3:
                txtPayer.setText(AppManager.INSTANCE.getPlayers(2).getName());
                listAux.remove(2);
                cbPlayer.setModel(new DefaultComboBoxModel(listAux.toArray()));
            break;
            case 4:
                txtPayer.setText(AppManager.INSTANCE.getPlayers(3).getName());
                listAux.remove(3);
                cbPlayer.setModel(new DefaultComboBoxModel(listAux.toArray()));
            break;
        }
        
    }

    private void closeWindow() {
        this.dispose();
    }
    
    private void showError(int erro) {
        String message;
        switch(erro){
            case 1:
                //Number format 
                message ="Please insert a number";
                JOptionPane.showMessageDialog(this, message);
            break;
            case 2:
                //all exception
                message ="Please insert a number";
                JOptionPane.showMessageDialog(this, message);
            break;
            case 3:
                //Invalid number of players
                message ="Invalid quantity";
                JOptionPane.showMessageDialog(this, message);
            break;
            case 4:
                message ="Player lost";
                JOptionPane.showMessageDialog(this, message);
            break;
        } 
    }
}
