/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ThreePlayer;

import Model.AppManager;
import View.AddMoney;
import View.RemoveMoney;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Gomez
 */
public class PlayersWindowThree extends javax.swing.JDialog {
    private java.awt.Frame parent;
    private float rentPlayer1;
    private float rentPlayer2;
    private float rentPlayer3;
    /**
     * Creates new form PlayersWindow
     */
    public PlayersWindowThree(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent=parent;
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CurrentMoneyPlayer1Three = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CurrentMoneyPlayer2Three = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        player2nameThree = new javax.swing.JLabel();
        player1nameThree = new javax.swing.JLabel();
        player3nameThree = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CurrentMoneyPlayer3Three = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        togglePlayer1 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        togglePlayer2 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        togglePlayer3 = new javax.swing.JToggleButton();
        JailCountPLayer1 = new javax.swing.JButton();
        JailCountPLayer2 = new javax.swing.JButton();
        JailCountPLayer3 = new javax.swing.JButton();
        txtMoneyRentPlayer1 = new javax.swing.JTextField();
        txtMoneyRentPlayer2 = new javax.swing.JTextField();
        txtMoneyRentPlayer3 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Current Money:");

        CurrentMoneyPlayer1Three.setEditable(false);

        jLabel2.setText("Current Money:");

        CurrentMoneyPlayer2Three.setEditable(false);

        jButton1.setText("Add Money");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add Money");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Remove Money");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Remove Money");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Finish");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setText("Current Money:");

        CurrentMoneyPlayer3Three.setEditable(false);

        jButton6.setText("Add Money");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Remove Money");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Pay");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Pay");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Pay");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Luck");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Community Box");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel4.setText("Jail:");

        togglePlayer1.setText("No jail free");
        togglePlayer1.setActionCommand("");
        togglePlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePlayer1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Jail:");

        togglePlayer2.setText("No jail free");
        togglePlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePlayer2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Jail:");

        togglePlayer3.setText("No jail free");
        togglePlayer3.setActionCommand("");
        togglePlayer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePlayer3ActionPerformed(evt);
            }
        });

        JailCountPLayer1.setText("0");
        JailCountPLayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JailCountPLayer1ActionPerformed(evt);
            }
        });

        JailCountPLayer2.setText("0");
        JailCountPLayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JailCountPLayer2ActionPerformed(evt);
            }
        });

        JailCountPLayer3.setText("0");
        JailCountPLayer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JailCountPLayer3ActionPerformed(evt);
            }
        });

        txtMoneyRentPlayer1.setEditable(false);

        txtMoneyRentPlayer2.setEditable(false);

        txtMoneyRentPlayer3.setEditable(false);

        jButton13.setText("Roll Dice");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton12))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(player3nameThree, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(togglePlayer3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JailCountPLayer3)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(togglePlayer1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JailCountPLayer1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(player2nameThree, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CurrentMoneyPlayer2Three, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(1, 1, 1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(togglePlayer2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JailCountPLayer2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMoneyRentPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jButton13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButton10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CurrentMoneyPlayer1Three, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMoneyRentPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(378, 388, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CurrentMoneyPlayer3Three, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(player1nameThree, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMoneyRentPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(player1nameThree, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player2nameThree, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CurrentMoneyPlayer2Three, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoneyRentPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(CurrentMoneyPlayer1Three, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoneyRentPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(togglePlayer1)
                    .addComponent(togglePlayer2)
                    .addComponent(JailCountPLayer1)
                    .addComponent(JailCountPLayer2))
                .addGap(18, 18, 18)
                .addComponent(player3nameThree, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CurrentMoneyPlayer3Three, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMoneyRentPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(togglePlayer3)
                    .addComponent(JailCountPLayer3))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton13))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddMoney addMoney = new AddMoney(parent,true,1,this,3);
        addMoney.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AddMoney addMoney = new AddMoney(parent,true,2,this,3);
        addMoney.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        RemoveMoney removeMoney = new RemoveMoney(parent,true,1,this,3);
        removeMoney.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        RemoveMoney removeMoney = new RemoveMoney(parent,true,2,this,3);
        removeMoney.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        AddMoney addMoney = new AddMoney(parent,true,3,this,3);
        addMoney.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        RemoveMoney removeMoney = new RemoveMoney(parent,true,3,this,3);
        removeMoney.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       PaymentWindowThree payment = new PaymentWindowThree(parent, true,1,this);
       payment.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        PaymentWindowThree payment = new PaymentWindowThree(parent, true,2,this);
        payment.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       PaymentWindowThree payment = new PaymentWindowThree(parent, true,3,this);
       payment.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        showLuck();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        showCommunityBox();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void togglePlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePlayer1ActionPerformed
        if(togglePlayer1.getText().equals("Jail free")){
            togglePlayer1.setText("No jail free");
        }else{
            togglePlayer1.setText("Jail free");
        }
    }//GEN-LAST:event_togglePlayer1ActionPerformed

    private void togglePlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePlayer2ActionPerformed
        if(togglePlayer2.getText().equals("Jail free")){
            togglePlayer2.setText("No jail free");
        }else{
            togglePlayer2.setText("Jail free");
        }
    }//GEN-LAST:event_togglePlayer2ActionPerformed

    private void togglePlayer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePlayer3ActionPerformed
        if(togglePlayer3.getText().equals("Jail free")){
            togglePlayer3.setText("No jail free");
        }else{
            togglePlayer3.setText("Jail free");
        }
    }//GEN-LAST:event_togglePlayer3ActionPerformed

    private void JailCountPLayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JailCountPLayer1ActionPerformed
        String text = JailCountPLayer1.getText();

        switch(text){
            case "0":
            JailCountPLayer1.setText("1");
            break;
            case "1":
            JailCountPLayer1.setText("2");
            break;
            case "2":
            JailCountPLayer1.setText("3");
            break;
            case "3":
            JailCountPLayer1.setText("0");
            break;
        }
    }//GEN-LAST:event_JailCountPLayer1ActionPerformed

    private void JailCountPLayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JailCountPLayer2ActionPerformed
        String text = JailCountPLayer2.getText();

        switch(text){
            case "0":
            JailCountPLayer2.setText("1");
            break;
            case "1":
            JailCountPLayer2.setText("2");
            break;
            case "2":
            JailCountPLayer2.setText("3");
            break;
            case "3":
            JailCountPLayer2.setText("0");
            break;
        }
    }//GEN-LAST:event_JailCountPLayer2ActionPerformed

    private void JailCountPLayer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JailCountPLayer3ActionPerformed
        String text = JailCountPLayer3.getText();

        switch(text){
            case "0":
            JailCountPLayer3.setText("1");
            break;
            case "1":
            JailCountPLayer3.setText("2");
            break;
            case "2":
            JailCountPLayer3.setText("3");
            break;
            case "3":
            JailCountPLayer3.setText("0");
            break;
        }
    }//GEN-LAST:event_JailCountPLayer3ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        Dice dice = new Dice(parent, true);
        dice.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CurrentMoneyPlayer1Three;
    private javax.swing.JTextField CurrentMoneyPlayer2Three;
    private javax.swing.JTextField CurrentMoneyPlayer3Three;
    private javax.swing.JButton JailCountPLayer1;
    private javax.swing.JButton JailCountPLayer2;
    private javax.swing.JButton JailCountPLayer3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel player1nameThree;
    private javax.swing.JLabel player2nameThree;
    private javax.swing.JLabel player3nameThree;
    private javax.swing.JToggleButton togglePlayer1;
    private javax.swing.JToggleButton togglePlayer2;
    private javax.swing.JToggleButton togglePlayer3;
    private javax.swing.JTextField txtMoneyRentPlayer1;
    private javax.swing.JTextField txtMoneyRentPlayer2;
    private javax.swing.JTextField txtMoneyRentPlayer3;
    // End of variables declaration//GEN-END:variables

    private void init() {
        player1nameThree.setText(AppManager.INSTANCE.getPlayers(0).getName());
        player2nameThree.setText(AppManager.INSTANCE.getPlayers(1).getName());
        player3nameThree.setText(AppManager.INSTANCE.getPlayers(2).getName());
        setCurrentMoneyPLayer1();
        setCurrentMoneyPLayer2();
        setCurrentMoneyPLayer3();
        
        rentPlayer1 = 0;
        rentPlayer2 = 0;
        rentPlayer3 = 0;
        txtMoneyRentPlayer1.setText(String.valueOf(rentPlayer1));
        txtMoneyRentPlayer2.setText(String.valueOf(rentPlayer2));
        txtMoneyRentPlayer3.setText(String.valueOf(rentPlayer3));
    }
    
    public void setCurrentMoneyPLayer1(){
        float million = AppManager.INSTANCE.getPlayers(0).getMoney()/ 1000000;
        
        if(million >=1){
            CurrentMoneyPlayer1Three.setText(String.format("%.2fM", AppManager.INSTANCE.getPlayers(0).getMoney()/ 1000000.0));
        }else{
            CurrentMoneyPlayer1Three.setText(String.format("%.2fK", AppManager.INSTANCE.getPlayers(0).getMoney()/ 1000.0));
        }
    }
    
    public void setCurrentMoneyPLayer2(){
        float million = AppManager.INSTANCE.getPlayers(0).getMoney()/ 1000000;
        
        if(million >=1){
            CurrentMoneyPlayer2Three.setText(String.format("%.2fM", AppManager.INSTANCE.getPlayers(1).getMoney()/ 1000000.0));
        }else{
            CurrentMoneyPlayer2Three.setText(String.format("%.2fK", AppManager.INSTANCE.getPlayers(1).getMoney()/ 1000.0));
        }
    }
    
    public void setCurrentMoneyPLayer3(){
        float million = AppManager.INSTANCE.getPlayers(0).getMoney()/ 1000000;
        
        if(million >=1){
            CurrentMoneyPlayer3Three.setText(String.format("%.2fM", AppManager.INSTANCE.getPlayers(2).getMoney()/ 1000000.0));
        }else{
            CurrentMoneyPlayer3Three.setText(String.format("%.2fK", AppManager.INSTANCE.getPlayers(2).getMoney()/ 1000.0));
        }
    }
    
     private void showLuck() {
        String luck = AppManager.INSTANCE.getRandomLuck();
        JOptionPane.showMessageDialog(this, luck);
    }

    private void showCommunityBox() {
        String communityBox = AppManager.INSTANCE.getRandomCommunityBox();
        JOptionPane.showMessageDialog(this, communityBox);
    }
    
    void setRentMoney(int player,float quantity) {
        switch(player){
            case 1:
                rentPlayer1 = rentPlayer1 + quantity;
                setRentMoneyPlayer1();
            break;
            case 2:
                rentPlayer2 = rentPlayer2 + quantity;
                setRentMoneyPlayer2();
            break;
            case 3:
                rentPlayer3 = rentPlayer3 + quantity;
                setRentMoneyPlayer3();
            break;
        }
    }

    private void setRentMoneyPlayer1() {
        float million = rentPlayer1/ 1000000;
        
        if(million >=1){
            txtMoneyRentPlayer1.setText(String.format("%.2fM", rentPlayer1/ 1000000.0));
        }else{
            txtMoneyRentPlayer1.setText(String.format("%.2fK", rentPlayer1/ 1000.0));
        }
    }

    private void setRentMoneyPlayer2() {
        float million = rentPlayer2/ 1000000;
        
        if(million >=1){
            txtMoneyRentPlayer2.setText(String.format("%.2fM", rentPlayer2/ 1000000.0));
        }else{
            txtMoneyRentPlayer2.setText(String.format("%.2fK", rentPlayer2/ 1000.0));
        }
    }
    
    private void setRentMoneyPlayer3() {
         float million = rentPlayer3/ 1000000;
        
        if(million >=1){
            txtMoneyRentPlayer3.setText(String.format("%.2fM", rentPlayer3/ 1000000.0));
        }else{
            txtMoneyRentPlayer3.setText(String.format("%.2fK", rentPlayer3/ 1000.0));
        }
    }
}
