/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.SixPlayer;

import Model.AppManager;
import Model.Player;
import View.FourPlayer.PlayersWindowFour;
import View.ThreePlayer.PlayersWindowThree;
import View.TwoPlayer.PlayersWindow;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Gomez
 */
public class AddMoneyBetter extends javax.swing.JDialog {
    private PlayersWindow window;
    private PlayersWindowThree windowThree;
    private PlayersWindowFour windowFour;
    private PlayersWindowSix windowSix;
    private int playerNumber;
    private Player player;
    /**
     * Creates new form AddMoneyBetter
     */
    public AddMoneyBetter(java.awt.Frame parent, boolean modal,int playerNumber,PlayersWindowSix windowSix) {
        super(parent, modal);
        initComponents();
        this.windowSix = windowSix;
        this.playerNumber = playerNumber;
        this.player = AppManager.INSTANCE.getPlayers(playerNumber-1);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        txtMoney = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblName.setText("jLabel1");

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName)
                .addGap(18, 18, 18)
                .addComponent(txtMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        closeWindow();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String insertMoney = txtMoney.getText();
        if(insertMoney.isEmpty()){
            showError(5);
        }else{
            if(!insertMoney.contains("M")&& !insertMoney.contains("K")){
                showError(6);
            }else{
                 float money;
                 if(insertMoney.contains("M")){
                    money = Float.parseFloat(insertMoney.split("M")[0])* 1000000;
                    player.setMoney(player.getMoney() + money);
                    windowSix.setAllCurrentMoney();
                    closeWindow();
                 }else{
                     money = Float.parseFloat(insertMoney.split("K")[0])*1000;
                     player.setMoney(player.getMoney() + money);
                     windowSix.setAllCurrentMoney();
                      closeWindow();
                 }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField txtMoney;
    // End of variables declaration//GEN-END:variables

    private void init() {
        lblName.setText(player.getName());
    }

    private void closeWindow() {
        this.dispose();
    }

    private void showError(int erro) {
        String message;
        switch(erro){
            case 1:
                //Number format 
                message ="Please insert a number";
                JOptionPane.showMessageDialog(this, message);
            break;
            case 2:
                //all exception
                message ="Please insert a number";
                JOptionPane.showMessageDialog(this, message);
            break;
            case 3:
                //Invalid money
                message ="Money must be positive";
                JOptionPane.showMessageDialog(this, message);
            break;
            case 4:
                //Invalid money
                message ="PLayer can't have negative money";
                JOptionPane.showMessageDialog(this, message);
            break;
            case 5:
                //Invalid money
                message ="Please insert a quantity";
                JOptionPane.showMessageDialog(this, message);
            break;
            case 6:
                //Invalid money
                message ="Please insert a quantity with million(M) ou milliar(K)";
                JOptionPane.showMessageDialog(this, message);
            break;
        } 
    }
}
