/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.AppManager;
import Model.Player;
import View.FourPlayer.PlayersWindowFour;
import View.ThreePlayer.PlayersWindowThree;
import java.awt.Frame;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Gomez
 */
public class PaymentPropriety extends javax.swing.JDialog {
    private float price;
    private LinkedList<Player> list;
    private PlayersWindowThree window;
    private PlayersWindowFour windowFour;
    private Player player;
    /**
     * Creates new form PaymentPropriety
     */
    public PaymentPropriety(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    public PaymentPropriety(Frame parent, boolean modal, PlayersWindowThree windowThree, Float price, Player player) {
        super(parent, modal);
        initComponents();
        this.window = windowThree;
        this.price = price;
        this.player = player;
        init();
    }
    
    public PaymentPropriety(Frame parent, boolean modal, PlayersWindowFour windowFour, Float price, Player player) {
        super(parent, modal);
        initComponents();
        this.windowFour = windowFour;
        this.price = price;
        this.player = player;
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPayer = new javax.swing.JLabel();
        txtReceiver = new javax.swing.JTextField();
        lblReceiver = new javax.swing.JLabel();
        cbPlayer = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblPayer.setText("Payer:");

        txtReceiver.setEditable(false);

        lblReceiver.setText("Receiver:");

        jLabel3.setText("Quantity:");

        jButton2.setText("Pay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPayer)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReceiver)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtQuantity)
                                .addComponent(cbPlayer, 0, 128, Short.MAX_VALUE))
                            .addComponent(txtReceiver, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(264, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPayer)
                    .addComponent(cbPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReceiver)
                    .addComponent(txtReceiver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Player p = (Player) cbPlayer.getSelectedItem();
        
        
        if(p.getMoney()< price){
            showError(1);
        }else{
            p.setMoney(p.getMoney() - price);
            player.setMoney(player.getMoney() + price);
            
            if(window != null){
                //janela tres
                window.setCurrentMoneyPLayer1();
                window.setCurrentMoneyPLayer2();
                window.setCurrentMoneyPLayer3();
            }else{
                //janela quatro
                windowFour.setCurrentMoneyPLayer1();
                windowFour.setCurrentMoneyPLayer2();
                windowFour.setCurrentMoneyPLayer3();
                windowFour.setCurrentMoneyPLayer4();
            }
            closeWindow();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        closeWindow();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbPlayer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblPayer;
    private javax.swing.JLabel lblReceiver;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtReceiver;
    // End of variables declaration//GEN-END:variables

    private void closeWindow() {
       this.dispose();
    }

    private void init() {
        txtReceiver.setText(player.getName());
        showMillion(price);
        txtQuantity.setEditable(false);
        LinkedList<Player> aux = new LinkedList<>();
        
        for(Player p:AppManager.INSTANCE.getPlayers()){
            if(p.getNumber() != player.getNumber()){
                aux.add(p);
            }
        }
        cbPlayer.setModel(new DefaultComboBoxModel(aux.toArray()));
    }
    
    private void showMillion(float money){
       float million = money/ 1000000;
        
        if(million >=1){
            txtQuantity.setText(String.format("%.2fM", money/ 1000000.0));
        }else{
            txtQuantity.setText(String.format("%.2fK", money/ 1000.0));
        }
   }

    private void showError(int erro) {
        String message;
        switch(erro){
            case 1:
                //Number format 
                message ="Player dont have money";
                JOptionPane.showMessageDialog(this, message);
            break;
        }
    }

    
}
