/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.FivePlayer;

import Model.AppManager;
import Model.Player;
import Model.Propriety;
import View.Dice;
import View.ProprietiesBuy;
import View.ShowPropriety;
import View.SixPlayer.AddMoneyBetter;
import View.SixPlayer.PaymentWindowSix;
import View.SixPlayer.RemoveMoneyBetter;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Carlos Gomez
 */
public class PlayersWindowFive extends javax.swing.JDialog {
    private float rentPlayer1;
    private float rentPlayer2;
    private float rentPlayer3;
    private float rentPlayer4;
    private float rentPlayer5;
    private float rentPlayer6;
    private java.awt.Frame parent;
    /**
     * Creates new form PlayersWindowFive
     */
    public PlayersWindowFive(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player1name = new javax.swing.JLabel();
        player2name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CurrentMoneyPlayer1 = new javax.swing.JTextField();
        txtMoneyRentPlayer1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CurrentMoneyPlayer2 = new javax.swing.JTextField();
        txtMoneyRentPlayer2 = new javax.swing.JTextField();
        jButton26 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        togglePlayer1 = new javax.swing.JToggleButton();
        JailCountPLayer1 = new javax.swing.JButton();
        togglePlayer2 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        JailCountPLayer2 = new javax.swing.JButton();
        player3name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CurrentMoneyPlayer3 = new javax.swing.JTextField();
        txtMoneyRentPlayer3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        togglePlayer3 = new javax.swing.JToggleButton();
        JailCountPLayer3 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        togglePlayer4 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        JailCountPLayer4 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        txtMoneyRentPlayer4 = new javax.swing.JTextField();
        CurrentMoneyPlayer4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        player4name = new javax.swing.JLabel();
        player5name = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CurrentMoneyPlayer5 = new javax.swing.JTextField();
        txtMoneyRentPlayer5 = new javax.swing.JTextField();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        togglePlayer5 = new javax.swing.JToggleButton();
        JailCountPLayer5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        player1name.setText("lbl");

        player2name.setText("lbl");

        jLabel1.setText("Current Money:");

        CurrentMoneyPlayer1.setEditable(false);

        txtMoneyRentPlayer1.setEditable(false);

        jLabel2.setText("Current Money:");

        CurrentMoneyPlayer2.setEditable(false);

        txtMoneyRentPlayer2.setEditable(false);

        jButton26.setText("Start Point");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton2.setText("Add Money");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Remove Money");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton11.setText("Pay");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton19.setText("Buy Propriety");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("Proprieties");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton1.setText("Add Money");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton25.setText("Start Point");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton3.setText("Remove Money");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton10.setText("Pay");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton17.setText("Buy Propriety");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("Proprieties");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jLabel5.setText("Jail:");

        togglePlayer1.setText("No jail free");
        togglePlayer1.setActionCommand("");
        togglePlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePlayer1ActionPerformed(evt);
            }
        });

        JailCountPLayer1.setText("0");
        JailCountPLayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JailCountPLayer1ActionPerformed(evt);
            }
        });

        togglePlayer2.setText("No jail free");
        togglePlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePlayer2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Jail:");

        JailCountPLayer2.setText("0");
        JailCountPLayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JailCountPLayer2ActionPerformed(evt);
            }
        });

        player3name.setText("lbl");

        jLabel3.setText("Current Money:");

        CurrentMoneyPlayer3.setEditable(false);

        txtMoneyRentPlayer3.setEditable(false);

        jButton6.setText("Add Money");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton27.setText("Start Point");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton7.setText("Remove Money");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton12.setText("Pay");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton23.setText("Buy Propriety");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setText("Proprieties");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jLabel7.setText("Jail:");

        togglePlayer3.setText("No jail free");
        togglePlayer3.setActionCommand("");
        togglePlayer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePlayer3ActionPerformed(evt);
            }
        });

        JailCountPLayer3.setText("0");
        JailCountPLayer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JailCountPLayer3ActionPerformed(evt);
            }
        });

        jButton14.setText("Luck");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Community Box");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("Roll Dice");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton5.setText("Finish");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        togglePlayer4.setText("No jail free");
        togglePlayer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePlayer4ActionPerformed(evt);
            }
        });

        jLabel8.setText("Jail:");

        JailCountPLayer4.setText("0");
        JailCountPLayer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JailCountPLayer4ActionPerformed(evt);
            }
        });

        jButton22.setText("Proprieties");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton21.setText("Buy Propriety");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton13.setText("Pay");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton9.setText("Remove Money");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton8.setText("Add Money");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton28.setText("Start Point");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        txtMoneyRentPlayer4.setEditable(false);

        CurrentMoneyPlayer4.setEditable(false);

        jLabel4.setText("Current Money:");

        player4name.setText("lbl");

        player5name.setText("lbl");

        jLabel9.setText("Current Money:");

        CurrentMoneyPlayer5.setEditable(false);

        txtMoneyRentPlayer5.setEditable(false);

        jButton29.setText("Add Money");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        jButton30.setText("Start Point");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        jButton31.setText("Remove Money");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton32.setText("Pay");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        jButton33.setText("Buy Propriety");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });

        jButton34.setText("Proprieties");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });

        jLabel10.setText("Jail:");

        togglePlayer5.setText("No jail free");
        togglePlayer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePlayer5ActionPerformed(evt);
            }
        });

        JailCountPLayer5.setText("0");
        JailCountPLayer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JailCountPLayer5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jButton16))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton15)))
                        .addGap(298, 298, 298)
                        .addComponent(jButton5)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton27))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CurrentMoneyPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMoneyRentPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(togglePlayer3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JailCountPLayer3))
                                    .addComponent(player3name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(161, 161, 161)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jButton13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton28))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CurrentMoneyPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMoneyRentPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(player4name, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(98, 98, 98))
                                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(togglePlayer4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JailCountPLayer4))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton25))
                                    .addComponent(player1name, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CurrentMoneyPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMoneyRentPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(149, 149, 149)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton26))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CurrentMoneyPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMoneyRentPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(player2name, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton30))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CurrentMoneyPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMoneyRentPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player5name, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(togglePlayer1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JailCountPLayer1)
                        .addGap(232, 232, 232)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(togglePlayer2)
                        .addGap(10, 10, 10)
                        .addComponent(JailCountPLayer2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(togglePlayer5)
                        .addGap(10, 10, 10)
                        .addComponent(JailCountPLayer5)
                        .addGap(170, 170, 170))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(player1name, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player2name, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(CurrentMoneyPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMoneyRentPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(jButton25))
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(22, 22, 22)
                                .addComponent(jButton10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(CurrentMoneyPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMoneyRentPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(jButton26))
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addGap(22, 22, 22)
                                .addComponent(jButton11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton20))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(player5name, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(CurrentMoneyPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoneyRentPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton29)
                            .addComponent(jButton30))
                        .addGap(18, 18, 18)
                        .addComponent(jButton31)
                        .addGap(22, 22, 22)
                        .addComponent(jButton32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(togglePlayer1)
                            .addComponent(JailCountPLayer1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(togglePlayer2)
                            .addComponent(JailCountPLayer2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(togglePlayer5)
                            .addComponent(JailCountPLayer5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(player4name, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(CurrentMoneyPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoneyRentPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton28))
                        .addGap(18, 18, 18)
                        .addComponent(jButton9)
                        .addGap(18, 18, 18)
                        .addComponent(jButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton22)
                        .addGap(110, 110, 110))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(player3name, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CurrentMoneyPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoneyRentPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton27))
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(togglePlayer3)
                                    .addComponent(JailCountPLayer3)
                                    .addComponent(jLabel8)
                                    .addComponent(togglePlayer4)
                                    .addComponent(JailCountPLayer4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton14)
                                    .addComponent(jButton15))
                                .addGap(13, 13, 13)
                                .addComponent(jButton16)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        AppManager.INSTANCE.getPlayers(1).setMoney(AppManager.INSTANCE.getPlayers(1).getMoney()+2000000);
        setCurrentMoneyPLayer2();
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AddMoneyBetter addMoney = new AddMoneyBetter(parent,true,2,this);
        addMoney.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        RemoveMoneyBetter removeMoney = new RemoveMoneyBetter(parent,true,2,this);
        removeMoney.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        PaymentWindowSix payment = new PaymentWindowSix(parent, true,2,this);
        payment.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        boolean hasProprietyToBuy = false;

        for(Propriety p:AppManager.INSTANCE.getProprieties()){
            if(!p.isIsOwned()){
                hasProprietyToBuy = true;
                break;
            }
        }

        if(hasProprietyToBuy){
            ProprietiesBuy buy = new ProprietiesBuy(parent, true, 1,this);
            buy.setVisible(true);
        }else{
            showError(2);
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        Player player = AppManager.INSTANCE.getPlayers(1);

        if(player.getProprieties().size() != 0){
            ShowPropriety show = new ShowPropriety(parent, true,1,this);
            show.setVisible(true);
        }else{
            showError(1);
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddMoneyBetter addMoney = new AddMoneyBetter(parent,true,1,this);
        addMoney.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        AppManager.INSTANCE.getPlayers(0).setMoney( AppManager.INSTANCE.getPlayers(0).getMoney()+2000000);
        setCurrentMoneyPLayer1();
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        RemoveMoneyBetter removeMoney = new RemoveMoneyBetter(parent,true,1,this);
        removeMoney.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        PaymentWindowSix payment = new PaymentWindowSix(parent, true,1,this);
        payment.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        boolean hasProprietyToBuy = false;

        for(Propriety p:AppManager.INSTANCE.getProprieties()){
            if(!p.isIsOwned()){
                hasProprietyToBuy = true;
                break;
            }
        }

        if(hasProprietyToBuy){
            ProprietiesBuy buy = new ProprietiesBuy(parent, true, 0,this);
            buy.setVisible(true);
        }else{
            showError(2);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        Player player = AppManager.INSTANCE.getPlayers(0);

        if(player.getProprieties().size() != 0){
            ShowPropriety show = new ShowPropriety(parent, true,0,this);
            show.setVisible(true);
        }else{
            showError(1);
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void togglePlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePlayer1ActionPerformed
        if(togglePlayer1.getText().equals("Jail free")){
            togglePlayer1.setText("No jail free");
        }else{
            togglePlayer1.setText("Jail free");
        }
    }//GEN-LAST:event_togglePlayer1ActionPerformed

    private void JailCountPLayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JailCountPLayer1ActionPerformed
        String text = JailCountPLayer1.getText();

        switch(text){
            case "0":
            JailCountPLayer1.setText("1");
            break;
            case "1":
            JailCountPLayer1.setText("2");
            break;
            case "2":
            JailCountPLayer1.setText("3");
            break;
            case "3":
            JailCountPLayer1.setText("0");
            break;
        }
    }//GEN-LAST:event_JailCountPLayer1ActionPerformed

    private void togglePlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePlayer2ActionPerformed
        if(togglePlayer2.getText().equals("Jail free")){
            togglePlayer2.setText("No jail free");
        }else{
            togglePlayer2.setText("Jail free");
        }
    }//GEN-LAST:event_togglePlayer2ActionPerformed

    private void JailCountPLayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JailCountPLayer2ActionPerformed
        String text = JailCountPLayer2.getText();

        switch(text){
            case "0":
            JailCountPLayer2.setText("1");
            break;
            case "1":
            JailCountPLayer2.setText("2");
            break;
            case "2":
            JailCountPLayer2.setText("3");
            break;
            case "3":
            JailCountPLayer2.setText("0");
            break;
        }
    }//GEN-LAST:event_JailCountPLayer2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        AddMoneyBetter addMoney = new AddMoneyBetter(parent,true,3,this);
        addMoney.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        AppManager.INSTANCE.getPlayers(2).setMoney( AppManager.INSTANCE.getPlayers(2).getMoney()+2000000);
        setCurrentMoneyPLayer3();
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        RemoveMoneyBetter removeMoney = new RemoveMoneyBetter(parent,true,3,this);
        removeMoney.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        PaymentWindowSix payment = new PaymentWindowSix(parent, true,3,this);
        payment.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        boolean hasProprietyToBuy = false;

        for(Propriety p:AppManager.INSTANCE.getProprieties()){
            if(!p.isIsOwned()){
                hasProprietyToBuy = true;
                break;
            }
        }

        if(hasProprietyToBuy){
            ProprietiesBuy buy = new ProprietiesBuy(parent, true, 2,this);
            buy.setVisible(true);
        }else{
            showError(2);
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        Player player = AppManager.INSTANCE.getPlayers(2);

        if(player.getProprieties().size() != 0){
            ShowPropriety show = new ShowPropriety(parent, true,2,this);
            show.setVisible(true);
        }else{
            showError(1);
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void togglePlayer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePlayer3ActionPerformed
        if(togglePlayer3.getText().equals("Jail free")){
            togglePlayer3.setText("No jail free");
        }else{
            togglePlayer3.setText("Jail free");
        }
    }//GEN-LAST:event_togglePlayer3ActionPerformed

    private void JailCountPLayer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JailCountPLayer3ActionPerformed
        String text = JailCountPLayer3.getText();

        switch(text){
            case "0":
            JailCountPLayer3.setText("1");
            break;
            case "1":
            JailCountPLayer3.setText("2");
            break;
            case "2":
            JailCountPLayer3.setText("3");
            break;
            case "3":
            JailCountPLayer3.setText("0");
            break;
        }
    }//GEN-LAST:event_JailCountPLayer3ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        showLuck();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        showCommunityBox();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        Dice dice = new Dice(parent, true);
        dice.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void togglePlayer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePlayer4ActionPerformed
        if(togglePlayer4.getText().equals("Jail free")){
            togglePlayer4.setText("No jail free");
        }else{
            togglePlayer4.setText("Jail free");
        }
    }//GEN-LAST:event_togglePlayer4ActionPerformed

    private void JailCountPLayer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JailCountPLayer4ActionPerformed
        String text = JailCountPLayer4.getText();

        switch(text){
            case "0":
            JailCountPLayer4.setText("1");
            break;
            case "1":
            JailCountPLayer4.setText("2");
            break;
            case "2":
            JailCountPLayer4.setText("3");
            break;
            case "3":
            JailCountPLayer4.setText("0");
            break;
        }
    }//GEN-LAST:event_JailCountPLayer4ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        Player player = AppManager.INSTANCE.getPlayers(3);

        if(player.getProprieties().size() != 0){
            ShowPropriety show = new ShowPropriety(parent, true,3,this);
            show.setVisible(true);
        }else{
            showError(1);
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        boolean hasProprietyToBuy = false;

        for(Propriety p:AppManager.INSTANCE.getProprieties()){
            if(!p.isIsOwned()){
                hasProprietyToBuy = true;
                break;
            }
        }

        if(hasProprietyToBuy){
            ProprietiesBuy buy = new ProprietiesBuy(parent, true, 3,this);
            buy.setVisible(true);
        }else{
            showError(2);
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        PaymentWindowSix payment = new PaymentWindowSix(parent, true,4,this);
        payment.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        RemoveMoneyBetter removeMoney = new RemoveMoneyBetter(parent,true,4,this);
        removeMoney.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        AddMoneyBetter addMoney = new AddMoneyBetter(parent,true,4,this);
        addMoney.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        AppManager.INSTANCE.getPlayers(3).setMoney( AppManager.INSTANCE.getPlayers(3).getMoney()+2000000);
        setCurrentMoneyPLayer4();
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        AddMoneyBetter addMoney = new AddMoneyBetter(parent,true,5,this);
        addMoney.setVisible(true);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        AppManager.INSTANCE.getPlayers(4).setMoney( AppManager.INSTANCE.getPlayers(4).getMoney()+2000000);
        setCurrentMoneyPLayer5();
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        RemoveMoneyBetter removeMoney = new RemoveMoneyBetter(parent,true,5,this);
        removeMoney.setVisible(true);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        PaymentWindowSix payment = new PaymentWindowSix(parent, true,5,this);
        payment.setVisible(true);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        boolean hasProprietyToBuy = false;

        for(Propriety p:AppManager.INSTANCE.getProprieties()){
            if(!p.isIsOwned()){
                hasProprietyToBuy = true;
                break;
            }
        }

        if(hasProprietyToBuy){
            ProprietiesBuy buy = new ProprietiesBuy(parent, true, 4,this);
            buy.setVisible(true);
        }else{
            showError(2);
        }
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        Player player = AppManager.INSTANCE.getPlayers(4);

        if(player.getProprieties().size() != 0){
            ShowPropriety show = new ShowPropriety(parent, true,4,this);
            show.setVisible(true);
        }else{
            showError(1);
        }
    }//GEN-LAST:event_jButton34ActionPerformed

    private void togglePlayer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePlayer5ActionPerformed
        if(togglePlayer5.getText().equals("Jail free")){
            togglePlayer5.setText("No jail free");
        }else{
            togglePlayer5.setText("Jail free");
        }
    }//GEN-LAST:event_togglePlayer5ActionPerformed

    private void JailCountPLayer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JailCountPLayer5ActionPerformed
        String text = JailCountPLayer5.getText();

        switch(text){
            case "0":
            JailCountPLayer5.setText("1");
            break;
            case "1":
            JailCountPLayer5.setText("2");
            break;
            case "2":
            JailCountPLayer5.setText("3");
            break;
            case "3":
            JailCountPLayer5.setText("0");
            break;
        }
    }//GEN-LAST:event_JailCountPLayer5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayersWindowFive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayersWindowFive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayersWindowFive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayersWindowFive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlayersWindowFive dialog = new PlayersWindowFive(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CurrentMoneyPlayer1;
    private javax.swing.JTextField CurrentMoneyPlayer2;
    private javax.swing.JTextField CurrentMoneyPlayer3;
    private javax.swing.JTextField CurrentMoneyPlayer4;
    private javax.swing.JTextField CurrentMoneyPlayer5;
    private javax.swing.JButton JailCountPLayer1;
    private javax.swing.JButton JailCountPLayer2;
    private javax.swing.JButton JailCountPLayer3;
    private javax.swing.JButton JailCountPLayer4;
    private javax.swing.JButton JailCountPLayer5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel player1name;
    private javax.swing.JLabel player2name;
    private javax.swing.JLabel player3name;
    private javax.swing.JLabel player4name;
    private javax.swing.JLabel player5name;
    private javax.swing.JToggleButton togglePlayer1;
    private javax.swing.JToggleButton togglePlayer2;
    private javax.swing.JToggleButton togglePlayer3;
    private javax.swing.JToggleButton togglePlayer4;
    private javax.swing.JToggleButton togglePlayer5;
    private javax.swing.JTextField txtMoneyRentPlayer1;
    private javax.swing.JTextField txtMoneyRentPlayer2;
    private javax.swing.JTextField txtMoneyRentPlayer3;
    private javax.swing.JTextField txtMoneyRentPlayer4;
    private javax.swing.JTextField txtMoneyRentPlayer5;
    // End of variables declaration//GEN-END:variables
private void showError(int erro) {
        String message;
        switch(erro){
            case 1:
                //Number format 
                message ="Dont have proprieties to show details";
                JOptionPane.showMessageDialog(this, message);
            break;
            case 2:
                //Number format 
                message ="All proprieties have owned";
                JOptionPane.showMessageDialog(this, message);
            break;
        }
    }

    private void showMillion(float money,JTextField field){
        float million = money/ 1000000;

       if(million >=1){
           field.setText(String.format("%.2fM", money/ 1000000.0));
       }else{
           field.setText(String.format("%.2fK", money/ 1000.0));
       }
    }

    private void setRentMoneyPlayer1() {
        showMillion(rentPlayer1, txtMoneyRentPlayer1);
    }
    
    private void setRentMoneyPlayer2() {
        showMillion(rentPlayer2, txtMoneyRentPlayer2);
    }
    
    private void setRentMoneyPlayer3() {
        showMillion(rentPlayer3, txtMoneyRentPlayer3);
    }
    
    private void setRentMoneyPlayer4() {
        showMillion(rentPlayer4, txtMoneyRentPlayer4);
    }
    
    private void setRentMoneyPlayer5() {
        showMillion(rentPlayer5, txtMoneyRentPlayer5);
    }
    
   
    private void updateRentMoney(){
        setRentMoneyPlayer1();
        setRentMoneyPlayer2();
        setRentMoneyPlayer3();
        setRentMoneyPlayer4();
        setRentMoneyPlayer5();
    }
    
    private void showLuck() {
        String luck = AppManager.INSTANCE.getRandomLuck();
        JOptionPane.showMessageDialog(this, luck);
    }

    private void showCommunityBox() {
        String communityBox = AppManager.INSTANCE.getRandomCommunityBox();
        JOptionPane.showMessageDialog(this, communityBox);
    }
    
     public void setRentMoney(int player,float quantity) {
        switch(player){
            case 1:
                rentPlayer1 = rentPlayer1 + quantity;
                setRentMoneyPlayer1();
            break;
            case 2:
                rentPlayer2 = rentPlayer2 + quantity;
                setRentMoneyPlayer2();
            break;
            case 3:
                rentPlayer3 = rentPlayer3 + quantity;
                setRentMoneyPlayer3();
            break;
            case 4:
                rentPlayer4 = rentPlayer4 + quantity;
                setRentMoneyPlayer4();
            break;
            case 5:
                rentPlayer5 = rentPlayer5 + quantity;
                setRentMoneyPlayer5();
            break;
            case 6:
                rentPlayer5 = rentPlayer5 + quantity;
                setRentMoneyPlayer5();
            break;
        }
    }
     
     private void init() {
        player1name.setText(AppManager.INSTANCE.getPlayers(0).getName());
        player2name.setText(AppManager.INSTANCE.getPlayers(1).getName());
        player3name.setText(AppManager.INSTANCE.getPlayers(2).getName());
        player4name.setText(AppManager.INSTANCE.getPlayers(3).getName());
        player5name.setText(AppManager.INSTANCE.getPlayers(4).getName());
        setAllCurrentMoney();
        
        rentPlayer1 = 0;
        rentPlayer2 = 0;
        rentPlayer3 = 0;
        rentPlayer4 = 0;
        rentPlayer5 = 0;
        rentPlayer6 = 0;
        txtMoneyRentPlayer1.setText(String.valueOf(rentPlayer1));
        txtMoneyRentPlayer2.setText(String.valueOf(rentPlayer2));
        txtMoneyRentPlayer3.setText(String.valueOf(rentPlayer3));
        txtMoneyRentPlayer4.setText(String.valueOf(rentPlayer4));
        txtMoneyRentPlayer5.setText(String.valueOf(rentPlayer5));
    }
    
    public void setCurrentMoneyPLayer1(){
        showMillion(AppManager.INSTANCE.getPlayers(0).getMoney(), CurrentMoneyPlayer1);
    }
    
    public void setCurrentMoneyPLayer2(){
        showMillion(AppManager.INSTANCE.getPlayers(1).getMoney(), CurrentMoneyPlayer2);
    }
    
    public void setCurrentMoneyPLayer3(){
        showMillion(AppManager.INSTANCE.getPlayers(2).getMoney(), CurrentMoneyPlayer3);
    }
    
    public void setCurrentMoneyPLayer4(){
        showMillion(AppManager.INSTANCE.getPlayers(3).getMoney(), CurrentMoneyPlayer4);
    }
    
    public void setCurrentMoneyPLayer5(){
        showMillion(AppManager.INSTANCE.getPlayers(4).getMoney(), CurrentMoneyPlayer5);
    }
    
    public void setAllCurrentMoney(){
        setCurrentMoneyPLayer1();
        setCurrentMoneyPLayer2();
        setCurrentMoneyPLayer3();
        setCurrentMoneyPLayer4();
        setCurrentMoneyPLayer5();
    }


}
